name: Create patch apk
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Save build timestamp
        id: set_build_timestamp
        run: echo "build_timestamp=$( date --utc +%Y%m%d-%H%M%S )" >> "$GITHUB_OUTPUT"
      - name: Install additional dev dependencies
        run: sudo apt-get update && sudo apt-get install --yes musl-tools
      - name: Install Rust target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Set up path
        run: ruby -e 'puts Gem.user_dir + "/bin"' >> "$GITHUB_PATH"
      - name: Install fpm
        run: gem install --user-install fpm
      - name: Running build script
        run: ./script/apk.sh
      - name: Save apk
        uses: actions/upload-artifact@v4
        with:
          name: "warrior4-apk-${{ steps.set_build_timestamp.outputs.build_timestamp }}"
          path: output/
